{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autocert.fullname" . }}
  namespace: {{ include "autocert.namespace" . }}
  labels:
    {{- include "autocert.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "autocert.selectorLabels" . | nindent 4 }}
{{- end }}