domains:
- name: example.com
  domains:
  - "*.example.com"
  - "example.com"
  dns: "dns_cf" # Cloudflare DNS API
  server: "https://acme-v02.api.letsencrypt.org/directory"
  email: "admin@example.com" # 证书申请使用的邮箱
  secrets:
  - namespace: "default"
    name: "example-com-tls"
  envs:
    CF_Key: "your-cloudflare-api-key"
    CF_Email: "your-cloudflare-email"

- name: another-example.com
  domains:
  - "*.another-example.com"
  - "another-example.com"
  dns: "dns_ali" # Aliyun DNS API
  server: "https://acme-v02.api.letsencrypt.org/directory"
  email: "webmaster@another-example.com" # 证书申请使用的邮箱
  secrets:
  - namespace: "default"
    name: "another-example-com-tls"
  - namespace: "ingress-nginx"
    name: "another-example-com-wildcard-tls"
  envs:
    Ali_Key: "your-aliyun-access-key-id"
    Ali_Secret: "your-aliyun-access-key-secret"
renewal:
  interval: 30d
  notify: true
acme:
  email: admin@example.com
  staging: false
  challenge:
    http:
      enabled: true
      port: 80
    dns:
      enabled: false
      provider: ""
logging:
  level: info
  format: json
